name: Build and Deploy FastAPI Docker Container

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}:latest .
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            sudo docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
            sudo docker stop ${{ env.DOCKER_REPO }}
            sudo docker rm ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}
            sudo docker rmi ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}:latest
            sudo docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}:latest
            sudo docker run -d -p 8080:8080 \
              -e OPENAI_API_KEY= ${{ env.OPENAI_API_KEY }}